name: hello_service
# description: A simple web server
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  http_server: ^0.9.6

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  test: ^1.6.0
  pedantic: ^1.8.0
