version: '3'

services:
    react-hello-client:
        image: react-hello-client:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        container_name: react-hello-client
        ports:
            - "8081:3000"
        volumes:
            - ./app:/app
        stdin_open: true
        tty: true

networks:
    default:
        external:
            name: mynetwork