version: '3'

services:
    hello-service:
        image: express-hello-service:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hello-service
        ports:
            - "8081:8080"
        #volumes:
        #    - ./app:/app
        stdin_open: true
        tty: true