version: '3'


services:
    dart-hello-service:
        image: dart-hello-service:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dart-hello-service
        ports:
            - "8080:8080"
        volumes:
            - ./app:/app
        stdin_open: true
        tty: true

networks:
    default:
        external:
            name: mynetwork