version: '3'

services:
    vue-hello-client:
        image: vue-hello-client:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vue-hello-client
        ports:
            - "8080:8080"
        volumes:
            - ./app:/app
        stdin_open: true
        tty: true

networks:
    default:
        external:
            name: mynetwork